Link-Buddy/back

src/main/java/com/linkbuddy/domain/link/LinkController.java, src/main/java/com/linkbuddy/domain/link/LinkRepository.java, src/main/java/com/linkbuddy/domain/link/LinkService.java, src/main/java/com/linkbuddy/domain/link/createLinkDto.java, src/main/java/com/linkbuddy/global/config/QueryDslConfig.java, src/main/java/com/linkbuddy/global/entity/Link.java, src/main/resources/application.properties
- LINK CRUD
- DTO 생성 중
- @Query 대신 queryDSL 고려
resolves #1
=> feat: link CRUD

src/main/java/com/linkbuddy/domain/buddy/BuddyController.java, src/main/java/com/linkbuddy/domain/buddy/BuddyService.java, src/main/java/com/linkbuddy/domain/buddy/dto/BuddyDTO.java, src/main/java/com/linkbuddy/domain/buddy/repository/BuddyUserRepository.java, src/main/java/com/linkbuddy/domain/user/UserController.java, src/main/java/com/linkbuddy/domain/user/UserService.java, src/main/java/com/linkbuddy/domain/user/dto/UserDTO.java, src/main/java/com/linkbuddy/domain/user/repository/UserRepository.java, src/main/java/com/linkbuddy/global/entity/Buddy.java, src/main/java/com/linkbuddy/global/entity/BuddyUser.java, src/main/java/com/linkbuddy/global/entity/User.java
- 회원 버디 그룹 탈퇴
- 친구초대 1) 회원 조회 (이메일) 2) 버디 회원 생성 3) 버디 회원 수정 (초대수락여부)
- BuddyUser, Buddy, User 테이블 comment 및 description 추가
resolves
=> feat: 회원버디그룹 탈퇴 & 친구초대

.gitignore, src/main/generated/com/linkbuddy/global/entity/QBuddyUser.java, src/main/java/com/linkbuddy/domain/category/CategoryController.java, src/main/java/com/linkbuddy/domain/category/CategoryDto.java, src/main/java/com/linkbuddy/domain/category/CategoryService.java, src/main/java/com/linkbuddy/domain/category/repository/CategoryCustomRepository.java, src/main/java/com/linkbuddy/domain/category/repository/CategoryCustomRepositoryImpl.java, src/main/java/com/linkbuddy/domain/category/repository/CategoryRepository.java, src/main/java/com/linkbuddy/domain/link/LinkController.java, src/main/java/com/linkbuddy/domain/link/LinkDto.java, src/main/java/com/linkbuddy/domain/link/LinkService.java, src/main/java/com/linkbuddy/domain/link/repository/LinkCustomRepository.java, src/main/java/com/linkbuddy/global/entity/Category.java
- linkgroup -> category 변경
- category
- model 생성 
- category CRU
- link
- link 응답 리팩토링
=> [Feature/#10] category CRU 생성 / link 

src/main/java/com/linkbuddy/domain/category/CategoryController.java, src/main/java/com/linkbuddy/domain/category/repository/CategoryCustomRepositoryImpl.java, src/main/java/com/linkbuddy/global/entity/Category.java
category로 이름 변경 시
groupname -> categoryname 필드명 수정 누락
resolves
=> fix: 필드명 수정 누락

build.gradle, src/main/java/com/linkbuddy/domain/test/TestController.java, src/main/java/com/linkbuddy/global/config/PrincipalDetails.java, src/main/java/com/linkbuddy/global/config/SecurityConfig.java, src/main/java/com/linkbuddy/global/config/SecurityPasswordEncoder.java, src/main/java/com/linkbuddy/global/entity/User.java
- Spring security 적용 (기본 로그인)
resolves
=> feat: Spring Security 설정 (기본 로그인)

src/main/generated/com/linkbuddy/global/entity/QLink.java, src/main/java/com/linkbuddy/domain/category/CategoryController.java, src/main/java/com/linkbuddy/domain/category/CategoryDto.java, src/main/java/com/linkbuddy/domain/category/CategoryService.java, src/main/java/com/linkbuddy/domain/category/repository/CategoryCustomRepository.java, src/main/java/com/linkbuddy/domain/category/repository/CategoryCustomRepositoryImpl.java, src/main/java/com/linkbuddy/domain/link/LinkController.java, src/main/java/com/linkbuddy/domain/link/LinkDto.java, src/main/java/com/linkbuddy/domain/link/LinkService.java, src/main/java/com/linkbuddy/domain/link/repository/LinkCustomRepository.java, src/main/java/com/linkbuddy/domain/link/repository/LinkCustomRepositoryImpl.java, src/main/java/com/linkbuddy/global/entity/Link.java
- link
- linkGroupId -> CategoryId로 수정
- 해당 링크들 카테고리 변경 수정 진행 중
- Category
- update 수정
- delete 생성 (해당하는 link들도 같이 삭제)
resolves #10
=> feat : Category, Link 기능 

src/main/java/com/linkbuddy/domain/buddy/BuddyService.java, src/main/java/com/linkbuddy/domain/user/UserController.java, src/main/java/com/linkbuddy/domain/user/UserService.java, src/main/java/com/linkbuddy/global/config/SecurityConfig.java, src/main/java/com/linkbuddy/global/entity/User.java
- 회원가입  / 로그인 암호화 적용
- 버디 생성시 alertTf / pinTf default 설정
resolves
=> feat: 회원가입 / 로그인 암호화 적용 (BCrypt)

src/main/java/com/linkbuddy/domain/buddyUser/repository/BuddyUserCustomRepository.java, src/main/java/com/linkbuddy/domain/buddyUser/repository/BuddyUserCustomRepositoryImpl.java, src/main/java/com/linkbuddy/domain/category/CategoryController.java, src/main/java/com/linkbuddy/domain/category/CategoryService.java, src/main/java/com/linkbuddy/domain/category/repository/CategoryCustomRepositoryImpl.java, src/main/java/com/linkbuddy/domain/link/LinkController.java, src/main/java/com/linkbuddy/domain/link/LinkDto.java, src/main/java/com/linkbuddy/domain/link/LinkService.java, src/main/java/com/linkbuddy/domain/link/repository/LinkCustomRepository.java, src/main/java/com/linkbuddy/domain/link/repository/LinkCustomRepositoryImpl.java
- 저번주 동작에 실패 했던 링크 카테고리변경 기능 완료
resolves
=> feat: 복수링크 카테고리 변경하기

.gitignore, build.gradle, src/main/java/com/linkbuddy/domain/user/UserController.java, src/main/java/com/linkbuddy/domain/user/UserService.java, src/main/java/com/linkbuddy/domain/user/dto/SignInDTO.java, src/main/java/com/linkbuddy/global/config/PrincipalDetails.java, src/main/java/com/linkbuddy/global/config/SecurityConfig.java, src/main/java/com/linkbuddy/global/config/jwt/JwtAuthenticationFilter.java, src/main/java/com/linkbuddy/global/config/jwt/JwtToken.java, src/main/java/com/linkbuddy/global/config/jwt/JwtTokenProvider.java, src/main/resources/application.properties
- JWT 설정 추가
- JwtAuthenticationFilter 상속시 GenericFilterBean -> OncePerRequestFilter로 변경
- Authorization header에 Bearer가 없을 경우에도 통과되도록 수정
resolves
=> feat: Spring security + JWT 설정

build.gradle, src/main/java/com/linkbuddy/domain/user/UserController.java, src/main/java/com/linkbuddy/domain/user/UserService.java, src/main/java/com/linkbuddy/domain/user/repository/UserCustomRepository.java, src/main/java/com/linkbuddy/domain/user/repository/UserCustomRepositoryImpl.java, src/main/java/com/linkbuddy/domain/user/repository/UserRepository.java, src/main/java/com/linkbuddy/global/config/PrincipalDetails.java, src/main/java/com/linkbuddy/global/config/SecurityConfig.java, src/main/java/com/linkbuddy/global/config/oauth/CustomOAuth2UserService.java, src/main/java/com/linkbuddy/global/config/oauth/OAuth2SuccessHandler.java, src/main/java/com/linkbuddy/global/config/oauth/OAuthAttributes.java, src/main/java/com/linkbuddy/global/entity/User.java
- 구글 OAuth2 로그인 추가 
- 실행 되긴 함. 추가 확인 필요
- findByEmail
- 기존 UserCostomRepository에 `findByEmail` 메소드명 변경
- UserResponse에 `findByEmail` 추가
- file은 아직 미저장
- service에서 originAttributes 미사용 => 확인필요
resolves
=> feat: 구글로그인 Oauth2

src/main/java/com/linkbuddy/domain/user/UserController.java, src/main/java/com/linkbuddy/domain/user/UserService.java, src/main/java/com/linkbuddy/domain/user/dto/UserDTO.java, src/main/java/com/linkbuddy/global/config/SecurityConfig.java, src/main/java/com/linkbuddy/global/config/oauth/CustomOAuth2UserService.java, src/main/java/com/linkbuddy/global/config/oauth/OAuth2SuccessHandler.java, src/main/java/com/linkbuddy/global/config/oauth/OAuthAttributes.java, src/main/java/com/linkbuddy/global/entity/User.java
- oauth2보완작업 
- tokenHandler 추가 (token발급)
- 로그인 시 social 업데이트
- userDTO에 마지막 로그인 일시 추가
- naver oauth2 추가작업 (https://github.com/Link-Buddy/back/pull/23 > 유진)
resolves
=> feat: oauth2 보완작업

src/main/java/com/linkbuddy/domain/buddy/BuddyController.java, src/main/java/com/linkbuddy/domain/buddy/dto/BuddyDTO.java, src/main/java/com/linkbuddy/domain/buddy/repository/BuddyCustomRepositoryImpl.java, src/main/java/com/linkbuddy/global/config/WebMvcConfig.java, src/main/java/com/linkbuddy/global/config/jwt/JwtTokenProvider.java
- CORS 설정 추가
- 버디 목록 조회 쿼리 컬럼 추가
resolves
=> feat: CORS 설정 추가 & 버디 목록 조회 수정

src/main/java/com/linkbuddy/domain/buddy/dto/BuddyDTO.java, src/main/java/com/linkbuddy/domain/buddyUser/BuddyUserController.java, src/main/java/com/linkbuddy/domain/buddyUser/BuddyUserService.java, src/main/java/com/linkbuddy/global/util/StatusEnum.java
=> fix: 버디 회원 생성(친구초대) 중복 차단

src/main/java/com/linkbuddy/domain/buddy/dto/BuddyDTO.java, src/main/java/com/linkbuddy/domain/buddyUser/BuddyUserController.java, src/main/java/com/linkbuddy/domain/buddyUser/BuddyUserService.java, src/main/java/com/linkbuddy/domain/buddyUser/repository/BuddyUserCustomRepository.java, src/main/java/com/linkbuddy/domain/buddyUser/repository/BuddyUserCustomRepositoryImpl.java, src/main/java/com/linkbuddy/global/config/jwt/SecurityUtil.java
- 회원 버디 초대 리스트 조회 API 추가
- spring-security userId 조회 공통 함수 생성
=> feat: 회원 버디 초대 리스트 조회 API 추가 및 spring-security userId 조회 공통 함수 생성

src/main/java/com/linkbuddy/domain/category/CategoryController.java, src/main/java/com/linkbuddy/domain/category/CategoryService.java, src/main/java/com/linkbuddy/domain/link/LinkController.java, src/main/java/com/linkbuddy/domain/link/LinkService.java, src/main/java/com/linkbuddy/domain/link/repository/LinkCustomRepository.java, src/main/java/com/linkbuddy/domain/link/repository/LinkCustomRepositoryImpl.java, src/main/java/com/linkbuddy/global/entity/Link.java
- 링크에 유저 연결
- 내 폴더에 해당하는 링크 조회
resolves
=> feat: 카테고리 조회 API 생성, 유저 연결

src/main/java/com/linkbuddy/domain/category/CategoryController.java, src/main/java/com/linkbuddy/domain/category/CategoryDto.java, src/main/java/com/linkbuddy/domain/category/CategoryService.java, src/main/java/com/linkbuddy/domain/category/repository/CategoryCustomRepository.java, src/main/java/com/linkbuddy/domain/category/repository/CategoryCustomRepositoryImpl.java, src/main/java/com/linkbuddy/domain/user/UserController.java, src/main/java/com/linkbuddy/domain/user/UserService.java, src/main/java/com/linkbuddy/domain/user/dto/ChangePasswordDto.java, src/main/java/com/linkbuddy/domain/user/dto/UserDTO.java, src/main/java/com/linkbuddy/domain/user/repository/UserCustomRepository.java, src/main/java/com/linkbuddy/domain/user/repository/UserCustomRepositoryImpl.java, src/main/java/com/linkbuddy/global/config/WebMvcConfig.java, src/main/java/com/linkbuddy/global/util/CustomException.java, src/main/java/com/linkbuddy/global/util/GlobalExceptionHandler.java, src/main/java/com/linkbuddy/global/util/ResponseMessage.java
[작업 내용]
- 유저
- 유저 가입 시 기본 폴더 생성
- 내 정보 조회
- 내 정보 수정
- 비밀번호 변경
- 카테고리
- 동일카테고리명 조회 
- 응답
- 공통응답에 message추가
- 공통예외처리 (customException)
=> feat: 카테고리, 내 정보, 예외처리

src/main/java/com/linkbuddy/domain/link/LinkController.java, src/main/java/com/linkbuddy/domain/link/LinkDto.java, src/main/java/com/linkbuddy/domain/link/LinkService.java, src/main/java/com/linkbuddy/global/entity/Link.java
- LinkDTO update 메소드 userId 추가
- updateLink, deleteLink spring security userId 조회 수정
resolves
=> fix: 링크 삭제, 수정 API 수정

src/main/java/com/linkbuddy/domain/category/CategoryDto.java, src/main/java/com/linkbuddy/domain/category/CategoryService.java
- buddy 카테고리 생성 직후 id추가하여 리턴
- 
resolves
=> feat: buddy 카테고리 생성 후 id 리턴

src/main/java/com/linkbuddy/domain/category/CategoryDto.java, src/main/java/com/linkbuddy/domain/category/repository/CategoryCustomRepositoryImpl.java, src/main/java/com/linkbuddy/domain/favorite/FavoriteController.java, src/main/java/com/linkbuddy/domain/favorite/FavoriteDto.java, src/main/java/com/linkbuddy/domain/favorite/FavoriteService.java, src/main/java/com/linkbuddy/domain/favorite/repository/FavoriteCustomRepository.java, src/main/java/com/linkbuddy/domain/favorite/repository/FavoriteCustomRepositoryImpl.java, src/main/java/com/linkbuddy/domain/favorite/repository/FavoriteRepository.java, src/main/java/com/linkbuddy/domain/link/LinkController.java, src/main/java/com/linkbuddy/domain/link/LinkDto.java, src/main/java/com/linkbuddy/domain/link/LinkService.java, src/main/java/com/linkbuddy/domain/link/repository/LinkCustomRepository.java, src/main/java/com/linkbuddy/domain/link/repository/LinkCustomRepositoryImpl.java, src/main/java/com/linkbuddy/domain/user/UserController.java, src/main/java/com/linkbuddy/domain/user/UserService.java, src/main/java/com/linkbuddy/domain/user/dto/UserDTO.java, src/main/java/com/linkbuddy/global/entity/Favorite.java
- 작업내용
- 개인/버디 각 카테고리가 가진 "링크 갯수" 추가반환
- 내가 등록한 링크 갯수
- 내가 즐겨찾기한 링크 갯수
- 즐겨찾기 DB
=> feat: 즐겨찾기 db 생성 / 링크 갯수

src/main/java/com/linkbuddy/domain/link/LinkController.java, src/main/java/com/linkbuddy/domain/link/LinkDto.java, src/main/java/com/linkbuddy/domain/link/LinkService.java, src/main/java/com/linkbuddy/domain/link/repository/LinkCustomRepository.java, src/main/java/com/linkbuddy/domain/link/repository/LinkCustomRepositoryImpl.java, src/main/java/com/linkbuddy/global/entity/Category.java, src/main/java/com/linkbuddy/global/entity/Link.java
- 링크 name, description 조회
- 내 링크, 버디 링크 조회
- relation 추가 (category-buddy, link-category)
=> feat: 링크 검색 API 생성

src/main/java/com/linkbuddy/domain/category/repository/CategoryCustomRepositoryImpl.java, src/main/java/com/linkbuddy/domain/favorite/FavoriteController.java, src/main/java/com/linkbuddy/domain/favorite/FavoriteService.java, src/main/java/com/linkbuddy/domain/favorite/repository/FavoriteCustomRepository.java, src/main/java/com/linkbuddy/domain/favorite/repository/FavoriteCustomRepositoryImpl.java, src/main/java/com/linkbuddy/domain/link/LinkController.java, src/main/java/com/linkbuddy/domain/link/LinkDto.java, src/main/java/com/linkbuddy/domain/link/LinkService.java, src/main/java/com/linkbuddy/domain/link/repository/LinkCustomRepository.java, src/main/java/com/linkbuddy/domain/link/repository/LinkCustomRepositoryImpl.java
- 즐겨찾기 활성화
- 즐겨찾기 권한 확인 (myLink)
- 링크 조회 시 즐겨찾기 여부 추가
resolves
=> feat: 즐겨찾기 활성화

src/main/java/com/linkbuddy/domain/link/LinkController.java, src/main/java/com/linkbuddy/domain/link/LinkService.java
- 링크 카테고리 이동 API requestparam -> pathVariable 로 수정
- securityUtil userId 받도록 수정
resolves
=> fix: 링크 카테고리 이동 API 수정

src/main/java/com/linkbuddy/domain/favorite/FavoriteController.java, src/main/java/com/linkbuddy/domain/favorite/repository/FavoriteCustomRepositoryImpl.java, src/main/java/com/linkbuddy/domain/link/LinkController.java, src/main/java/com/linkbuddy/domain/link/LinkDto.java, src/main/java/com/linkbuddy/domain/link/LinkService.java, src/main/java/com/linkbuddy/domain/link/repository/LinkCustomRepository.java, src/main/java/com/linkbuddy/domain/link/repository/LinkCustomRepositoryImpl.java, src/main/java/com/linkbuddy/domain/user/dto/UserDTO.java
- 내가 등록한 링크 및 갯수
- 개인, 버디 join하여 노출
- 즐겨찾는 링크 및 갯수
resolves
=> 즐겨찾기 링크 & 내가 등록한 링크

build.gradle, src/main/java/com/linkbuddy/domain/category/CategoryService.java, src/main/java/com/linkbuddy/domain/link/LinkController.java, src/main/java/com/linkbuddy/domain/link/LinkDto.java, src/main/java/com/linkbuddy/domain/link/LinkService.java
Link
- link preview 데이터 조회
- 링크 조회 수정 (카테고리 데이터 추가, 링크 preview 데이터 추가) 
Category
- 카테고리 데이터 조회
resolves
=> feat: link preview 데이터 조회 추가 & 링크 조회 수정 & 카테고리 데이터 조회 추가

src/main/java/com/linkbuddy/domain/link/LinkController.java, src/main/java/com/linkbuddy/domain/link/LinkService.java, src/main/java/com/linkbuddy/domain/link/repository/LinkCustomRepository.java, src/main/java/com/linkbuddy/domain/link/repository/LinkCustomRepositoryImpl.java
=> feat: 최근 본 링크 조회

src/main/java/com/linkbuddy/global/config/jwt/SecurityUtil.java, src/main/java/com/linkbuddy/global/config/oauth/OAuthAttributes.java
=> fix : 소셜로그인 claims에 email 삽입

src/main/java/com/linkbuddy/domain/user/UserController.java
회원가입 API 수정 (RequestBody 추가)
resolves
=> fix: 회원가입 API 수정

src/main/java/com/linkbuddy/domain/link/LinkController.java, src/main/java/com/linkbuddy/domain/link/LinkDto.java, src/main/java/com/linkbuddy/domain/link/LinkService.java
=> feat: 즐겨찾기 로직에 imageUrl 추가

src/main/java/com/linkbuddy/domain/buddy/repository/BuddyCustomRepositoryImpl.java, src/main/java/com/linkbuddy/domain/buddy/repository/BuddyRepository.java, src/main/java/com/linkbuddy/domain/buddyUser/BuddyUserController.java, src/main/java/com/linkbuddy/domain/buddyUser/BuddyUserService.java
- 해당 user가 방장인지 확인하는 기능 추가 (버디 삭제/나가기 구분을 위함)
- 버디 리스트 조회시 정렬 (pinTf, updatedAt 기준)
resolves
=> fix: user 방장인지 확인 & 버디 삭제/나가기 수정 & 버디 리스트 조회시 정렬 추가

src/main/java/com/linkbuddy/domain/buddyUser/BuddyUserService.java, src/main/java/com/linkbuddy/domain/buddyUser/repository/BuddyUserCustomRepository.java, src/main/java/com/linkbuddy/domain/buddyUser/repository/BuddyUserCustomRepositoryImpl.java, src/main/java/com/linkbuddy/domain/link/LinkController.java, src/main/java/com/linkbuddy/domain/link/LinkService.java, src/main/java/com/linkbuddy/domain/link/repository/LinkCustomRepository.java, src/main/java/com/linkbuddy/domain/link/repository/LinkCustomRepositoryImpl.java
- 버디링크 > 내링크보기로 사용 중이었음
- 버디id 받아서 -> 버디id있으면 버디링크 조회하기로 변경
- 미리보기 이미지 가져오기 메소드 분리 
resolves
=> feat: 버디링크 생성
